version: '3.9'
services:
  vue-app:
    container_name: vue-app
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app 
    ports:
      - "3000:3000"
